on:
  pull_request:
  push:
    branches: ["master"]
name: Go Test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    uses: pl-strflt/uci/.github/workflows/go-test.yml@v0.0
