name: Releaser
on:
  push:
    paths: [ 'version.json' ]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  releaser:
    uses: pl-strflt/uci/.github/workflows/releaser.yml@v0
